### ISSUE TITLE
og:tags

### ISSUE THREAD

**Issue by Kriesse** [cssconf/blog-content#7]
In order to make sharing on facebook etc. more effective, each blog post should have correct og:tags (title, image, description…)

it currently doesn't work:
https://developers.facebook.com/tools/debug/sharing/?q=http%3A%2F%2Fblog.cssconf.eu%2F2017%2F02%2F22%2Ffirst-speaker-announcement-cssconf-eu-2017%2F%3Fpreview

**Comment by lukaszklis** [comment]
![image](https://cloud.githubusercontent.com/assets/11782/23189202/22e28c14-f892-11e6-8478-7fe7eb31ee81.png)
